version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: snappie-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 113333555555
      POSTGRES_DB: snappie_photobooth
    ports:
      - "5432:5432"
    volumes:
      - snappie_data:/var/lib/postgresql/data

volumes:
  snappie_data:
